import { pages, workflow, scope, contactStatus } from '../site.mjs';

export function escapeHtml(text) {
  return text.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
}

function workflowNav(slug) {
  return `<nav class="workflow-nav" aria-label="作る順番"><ol>${workflow.map((step, i) => `<li><a href="${slug === 'beginner' ? '' : 'beginner.html'}#${step.id}"><span class="sequence-number">${i + 1}</span>${step.short}</a></li>`).join('')}</ol></nav>`;
}

export function expandContent(source, slug) {
  return source.replace(/\{\{\s*([\w-]+)\s*\}\}/g, (_, key) => {
    if (key === 'scope') return `<p class="scope-inline">${scope}</p>`;
    if (key === 'workflow') return workflowNav(slug);
    if (key === 'contact-status') return contactStatus;
    if (key.startsWith('step-')) {
      const index = workflow.findIndex(step => step.id === key.slice(5));
      if (index !== -1) return `<p class="flow-step">STEP ${index + 1}</p>`;
    }
    throw new Error(`Unknown content token: ${key} (${slug})`);
  });
}

export function layout(page, source) {
  const home = page.slug === 'index';
  const contact = page.slug === 'contact';
  const footerLinks = pages.filter(item => item.slug !== 'contact').map(item => `<a href="${item.slug}.html"${item.slug === page.slug ? ' aria-current="page"' : ''}>${item.label}</a>`).join('\n');
  const participantContact = `<aside class="participant-contact" aria-label="ワークショップ参加後のご相談">
<a href="contact.html">ワークショップ参加後のご相談 →</a>
<p>参加された方の、標本制作についてのご質問はこちらへ。</p>
<p class="participant-contact-status">${contactStatus}</p>
</aside>`;
  const main = expandContent(source, page.slug).replace('</main>', `${!home && !contact ? participantContact : ''}\n</main>`);
  return `<!doctype html>
<!-- Generated by npm run build. Edit content/guides and src, not this file. -->
<html lang="ja" id="page-top">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<meta name="description" content="${escapeHtml(page.description)}" />
<title>${escapeHtml(page.title || `${page.label}｜昆虫標本ガイド`)}</title>
<link rel="stylesheet" href="styles.css" />
</head>
<body>
<a class="skip-link" href="#main-content">本文へ</a>
<header class="site-header${home ? ' home-header' : ''}">
<a class="brand" href="index.html"><span>BOOM INSECT</span><strong>昆虫標本ガイド</strong></a>
${home ? '' : '<a class="guide-index-link" href="index.html#choose-guide">← ガイド一覧へ</a>'}
</header>
${main.replace('<main', '<main id="main-content"')}
<footer class="site-footer">
<p><strong>BOOM INSECT</strong>｜昆虫標本ガイド</p>
<nav class="footer-nav" aria-label="フッターのサイト案内">${footerLinks}</nav>
<p class="site-scope">${scope}</p>
</footer>
</body>
</html>
`;
}
