// Set src to a path below public (e.g. images/home/hero.webp) when an owned photo is ready.
// A null src deliberately reserves the requested photo frame without requesting a missing file.
export const media = {
  hero: { src: 'images/home/hero.webp', label: 'メイン写真', alt: '甲虫の姿が分かるメイン写真', width: 1600, height: 1200, position: '65% 50%', caption: '' },
  'card-beginner': { src: 'images/guides/beginner/tools.webp', label: '道具の写真', alt: '標本制作に使う道具', width: 1200, height: 1200 },
  'card-intermediate': { src: 'images/home/card-intermediate.webp', label: '甲虫の写真', alt: '形や色の異なる四体の甲虫標本を並べた写真', width: 1600, height: 1200 },
  'card-adults': { src: 'images/home/card-adults.webp', label: '標本とラベル', alt: 'クワガタの標本と、種名・採集地・採集時期を書いたラベル', width: 1200, height: 900, position: '50% 25%' },
  'card-home': { src: 'images/home/card-home.webp', label: '軟化の写真', alt: '水に浸して軟化させる甲虫', width: 1200, height: 1200 },
  tools: { src: 'images/guides/beginner/tools.webp', label: '使う道具の写真', alt: 'スタイロフォームの作業台など、今回使う七つの道具', width: 1200, height: 1200 },
  'surface-drying': { src: 'images/guides/beginner/surface-drying.webp', label: '軟化後の水気を取る写真', alt: '吸水用の紙の上に置いた軟化後の甲虫', width: 1200, height: 1200 },
  'body-height': { src: 'images/guides/beginner/body-height.webp', label: 'クワガタの体高の写真', alt: '横から見たクワガタのからだの厚みと脚', width: 1200, height: 1200 },
  'recess-mark': { src: 'images/guides/beginner/recess-mark.webp', label: 'くぼみの位置を決める写真', alt: 'クワガタの体のそばにピンでくぼみの位置を示した作業台', width: 1200, height: 1200, caption: '作業台にくぼみの位置を付けたところ' },
  'recess-made': { src: 'images/guides/beginner/recess-made.webp', label: 'くぼみを作った写真', alt: 'クワガタのそばにくぼみを作ったスタイロフォームの作業台', width: 1200, height: 1200, caption: 'くぼみを作ったあとの作業台' },
  'legs-open': { src: 'images/guides/beginner/legs-open.webp', label: '脚をひろげた写真', alt: 'おなか側から見た、脚をひろげたクワガタ', width: 1200, height: 1200, caption: 'おなか側から見た、脚をひろげた状態' },
  'body-in-recess': { src: 'images/guides/beginner/body-in-recess.webp', label: 'くぼみに置いた写真', alt: '背中を上にして作業台のくぼみに置いたクワガタ', width: 1200, height: 1200, caption: '背中を上にして、くぼみに置いた状態' },
  fixation: { src: 'images/guides/beginner/fixation.webp', label: 'からだを固定した写真', alt: '作業台の昆虫針で固定用バンドを留め、クワガタのからだを固定した状態', width: 1200, height: 1200, caption: 'まず、バンドでからだを固定' },
  'jaw-fixation': { src: 'images/guides/beginner/jaw-fixation.webp', label: '大顎を支えた写真', alt: 'からだを固定したあと、大顎のまわりに針を立てたクワガタ', width: 1200, height: 1200, caption: '次に、大顎の向きを支える' },
  legs: { src: 'images/guides/beginner/legs.webp', label: '脚の位置を整える写真', alt: '作業台に固定したクワガタの六本の脚を、針で支えながら整えている全体写真', width: 1200, height: 1200, caption: '脚の位置を整えている全体の様子' },
  'legs-closeup': { src: 'images/guides/beginner/legs-closeup.webp', label: '脚の位置の拡大写真', alt: 'クワガタのからだの近くの脚と、作業台に立てた針を拡大した写真', width: 1200, height: 1200, caption: '脚と針の位置を近くで見たところ' },
  tarsi: { src: 'images/guides/beginner/tarsi.webp', label: '跗節を整える写真', alt: '作業台に固定したクワガタの脚先の跗節を、周りに立てた針で支えている写真', width: 1200, height: 1200, caption: '腿節と脛節を整えたあと、跗節の向きを決める' },
  'tarsi-closeup': { src: 'images/guides/beginner/tarsi-closeup.webp', label: '後脚の跗節の拡大写真', alt: 'クワガタの後脚の跗節と爪を、作業台に立てた針とともに近くで写した写真', width: 1200, height: 1200, caption: '後脚の跗節を近くで見たところ' },
  antennae: { src: 'images/guides/beginner/antennae-side.webp', label: '脚先と触角を横から見る写真', alt: 'クワガタの脚先と触角を横から見て、作業台の針との高さの違いが分かる写真', width: 1200, height: 1200, caption: '横から脚先と触角の高さを見る' },
  'antennae-overview': { src: 'images/guides/beginner/antennae-overview.webp', label: '脚先と触角を上から見る写真', alt: '脚先と触角を整えたクワガタを、作業台の上から見た全体写真', width: 1200, height: 1200, caption: '上から脚先と触角の位置を見る' },
  'finish-front': { src: 'images/guides/beginner/finish-front.webp', label: '仕上げを前から見る写真', alt: '大顎と前脚の位置を正面から見た、作業台に固定中のクワガタ', width: 1200, height: 1200, caption: '前から見た大顎と前脚' },
  'finish-side': { src: 'images/guides/beginner/finish-side.webp', label: '仕上げを横から見る写真', alt: '作業台に固定中のクワガタの大顎と前脚を横から見た写真', width: 1200, height: 1200, caption: '横から見た大顎と脚先' },
  'finish-rear': { src: 'images/guides/beginner/finish-rear.webp', label: '仕上げを後ろから見る写真', alt: '作業台に固定中のクワガタの後脚と跗節を後ろから見た写真', width: 1200, height: 1200, caption: '後ろから見た後脚と跗節' },
  drying: { src: 'images/guides/beginner/drying.webp', label: '乾燥中のケースの写真', alt: '針とバンドで固定したクワガタをスタイロフォームの作業台ごと透明ケースに入れ、ふたを開けて乾かしている状態', width: 1200, height: 1200, caption: '固定したままケースへ。ふたを開けて乾かす' },
  label: { src: null, label: 'ラベルの写真', alt: '採集と制作の情報を区別したラベルと標本の対応', width: 1000, height: 650 },
  'softening-paper': { src: null, label: '湿度容器の配置写真', alt: '湿った紙と乾いた小皿を隔てて甲虫を置いた容器', width: 1000, height: 650 },
  'softening-water': { src: null, label: 'お湯から取り出す手元写真', alt: '甲虫の体を下からすくって取り出す様子', width: 1000, height: 650 },
  comparison: { src: 'images/guides/intermediate/comparison.webp', label: '配置を見比べる写真', alt: '昆虫標本の配置を見比べるための写真', width: 3781, height: 2836 }
};
